package = koopa.cobol.grammar.dependency

static.WORD        = koopa.core.data.tags.SyntacticTag
static.NUMBER      = koopa.core.data.tags.SyntacticTag
static.SEPARATOR   = koopa.core.data.tags.SyntacticTag
static.WHITESPACE  = koopa.core.data.tags.SyntacticTag
static.END_OF_LINE = koopa.core.data.tags.SyntacticTag
